version: 2

jobs:
    test:
      docker:
        - image: continuumio/anaconda3:5.0.1
      resource_class: arm.medium
      steps:
        - checkout
        - run:
            command: |
              conda update conda
              conda env create -f data/arm64.yml
              source activate somnus
              pip install -e .
              pytest tests

workflows:
  version: 2
  all:
    jobs:
      - test
