version: 2

jobs:
    test:
      docker:
        - image: continuumio/anaconda3:5.0.1
      steps:
        - checkout
        - run:
            command: |
              conda update conda
              conda env create -f data/envi/x86.yaml
              source activate zx86
              pip install -e .
              pytest tests

workflows:
  version: 2
  all:
    jobs:
      - test
